Traceback (most recent call last):
  File "/Users/danielbeller/pipp39/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/danielbeller/pipp39/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/danielbeller/pipp39/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/danielbeller/pipp39/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/danielbeller/pipp39/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/danielbeller/pipp39/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/danielbeller/pipp39/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
initfilenames = create_init_state(
    (whole_Lx, whole_Ly, whole_Lz),
    S,
    initfilename_prefix,
    nx_function_string,
    ny_function_string,
    nz_function_string,
    mpi_num_processes=mpi_num_processes,
)
print(initfilenames)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Input [0;32mIn [4][0m, in [0;36m<module>[0;34m[0m
[0;32m----> 1[0m initfilenames [38;5;241m=[39m [43mcreate_init_state[49m[43m([49m
[1;32m      2[0m [43m    [49m[43m([49m[43mwhole_Lx[49m[43m,[49m[43m [49m[43mwhole_Ly[49m[43m,[49m[43m [49m[43mwhole_Lz[49m[43m)[49m[43m,[49m
[1;32m      3[0m [43m    [49m[43mS[49m[43m,[49m
[1;32m      4[0m [43m    [49m[43minitfilename_prefix[49m[43m,[49m
[1;32m      5[0m [43m    [49m[43mnx_function_string[49m[43m,[49m
[1;32m      6[0m [43m    [49m[43mny_function_string[49m[43m,[49m
[1;32m      7[0m [43m    [49m[43mnz_function_string[49m[43m,[49m
[1;32m      8[0m [43m    [49m[43mmpi_num_processes[49m[38;5;241;43m=[39;49m[43mmpi_num_processes[49m[43m,[49m
[1;32m      9[0m [43m)[49m
[1;32m     10[0m [38;5;28mprint[39m(initfilenames)

[0;31mTypeError[0m: create_init_state() got multiple values for argument 'mpi_num_processes'
TypeError: create_init_state() got multiple values for argument 'mpi_num_processes'

